language: php

php:
  - 7.0
  - 7.1
  - master

script:
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=~/.phpenv/versions/$(phpenv version-name)/bin/php php ~/.phpenv/versions/$(phpenv version-name)/lib/php/build/run-tests.php -c ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini -q -x --show-diff
